#!/usr/bin/env bash
#  install nginx and configure it to listen to port 80 and print "Hello world"

apt-get update
apt-get -y install nginx
#ufw allow 'Nginx HTTP',
echo "Hello World!" > /var/www/html/index.html
service nginx start
