#!/usr/bin/env bash
#  install nginx and configure it to listen to port 80 and print "Hello world"

apt-get update
apt-get -y install nginx
#service nginx start
# allow the firewall to access port 80
# ufw allow 'Nginx HTTP'

#grant ownership and permission to the file pathcontaining the nginx file
# sudo chown -R "$USER":"$USER" /var/www/html
# sudo chmod 755 /var/www

#back up the original nginx-debian.html file
#cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bck
#echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# echo "Hello World!" | tee /usr/share/nginx/html/index.html > /dev/null

echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx start

#echo -e "Nginx installed and configured"
