#!/usr/bin/env bash
#  install nginx and configure it to listen to port 80 and print "Hello world"

sudo apt-get update
sudo apt-get -y install nginx
sudo serrvice nginx start
# allow the firewall to access port 80
ufw allow 'Nginx HTTP'

#grant ownership and permission to the file pathcontaining the nginx file
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod 755 /var/www

#back up the original nginx-debian.html file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bck
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# redirect to a different page
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=G_AEL-Xo5l8 permanent;' /etc/nginx/sites-available/default

# configure 404 not found page
echo "Ceci n'est pas une page" >> /var/www/html/error404.html
sudo sed -i '25i\      error_page 404 /error404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
