#!/usr/bin/env bash
#Write a Bash script that displays the (username, user i, home directory path for the user)of the file /etc/passwd.

file="/etc/passwd"
while IFS= read -r line
do
	uname="$(echo "$line" | cut -d":" -f1)"
	g_ID="$(echo "$line" | cut -d":" -f4)"
	home_dir="$(echo "$line" | cut -d":" -f6)"
	shell="$(echo "$line" | cut -d":" -f7)"
	u_ID="$(echo "$line" | cut -d":" -f3)"
	pass="$(echo "$line" | cut -d":" -f2)"
	info="$(echo "$line" | cut -d":" -f5)"

	echo "The user $uname is part of the $g_ID gang, lives in $home_dir and rides $shell. $u_ID's place is protected by the passcode $pass, more info about the user here: $info"
done < "$file"
