#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays bad luck, good luck for the 4th,8th loop iteration and  Best School for the other iterations

iteration=1
while [ $iteration -le 10 ]
do
	#echo "Best School"
	if [ $iteration -eq 4 ]
	then
		echo "bad luck"
	elif [ $iteration -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	iteration=$((iteration + 1))
done
