#!/usr/bin/env bash
# configure a ufw to block all incoming traffic except ports 22,80,443

sudo apt install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo enable
sudo ufw status verbose
