#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
#The checker is running on Docker

cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2  //g" ~/hosts.new
sed -i "s/.*facebook.com//g" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
