#!/usr/bin/env bash
# Write a Bash script that creates an RSA key pair.
# Requirements:
# 1) Name of the created private key must be school
# 2) Number of bits in the created key to be created 4096
# 3) The created key must be protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -f school -N betty
